### ISSUE TITLE
Stop using the creppy badly-named printf and use NodeJS util.format

### ISSUE THREAD

**Issue by Artoria2e5** [wfjsw/telegram2irc-bot#11]
https://nodejs.org/api/util.html#util_util_format_format

**Comment by Artoria2e5** [comment]
Oh well, that one doesn't seem to support any advanced things even `%NUM$FORMAT`……Let's use `sprintf` or `string-format`.

**Comment by wfjsw** [comment]
I prefer xxx + xxx + xxx (rush

**Comment by Arthur2e5** [comment]
Do you really need to assign people? Oh my this is crazy and silly…

**Comment by 910JQK** [comment]
Simply a function is enough for our requirement. Despite the ugly current version, a more robust one is available in the es6 branch.

**Comment by Artoria2e5** [comment]
Then I will say using replace is pointless and simple `+` is better.

**Comment by 910JQK** [comment]
Using `+` breaks string literal into pieces. It is not tidy and inconvenient when modifying.

**Comment by wfjsw** [comment]
CC @910JQK 
how hard is master->es6 transition for end users?

**Comment by 910JQK** [comment]
The biggest problem is some old versions of Node.js does not support ES6. Servers using Debian stable may suffer that.

**Comment by wfjsw** [comment]
coz I can write classic jabasukuriputo only, I will not be able to modify the es6 code without producing 80+ bug-fix commits

**Comment by farseerfc** [comment]
running ES6 is not a problem here... But I care about API changes

**Comment by Artoria2e5** [comment]
I don't think tg2irc bot is intended to expose any APIs for user use.
