### ISSUE TITLE
Custom nickname mapping in tg, and by default prefer tg username over Name.

### ISSUE THREAD

**Issue by Artoria2e5** [wfjsw/telegram2irc-bot#5]

**Comment by 910JQK** [comment]
If demanded, I will implement your feature requests next weekend or later.

**Comment by 910JQK** [comment]
@wfjsw 
I implemented secure connection config item and line count limit, but I wrote the code without testing because I had no condition to test it. Please test it carefully.

**Comment by wfjsw** [comment]
got it.

**Comment by 910JQK** [comment]
In addition, the config file <code>config.js</code> got so large that it should turn into JSON format.

**Comment by wfjsw** [comment]
Can change it directly without modify `index.js`, putting it later.

**Comment by Artoria2e5** [comment]
``` JavaScript
try {
  require that file stuff maybe but I think it is in node
  open blah file
  config = JSON.blah read blah
} catch {
  config = require blah
  try {
    open blah file w
    write JSON.stringify blah
  } catch { give a fuck; }
}
```

**Comment by 910JQK** [comment]
b3ffefb
Implemented. (in es6 branch)
